GET http://localhost:8083/api/v1/users
Accept: application/json


###

POST http://localhost:8083/api/v1/users/create
Content-Type: application/json

{"username":"Hello",
  "contextId": "",
  "email":"teste@email.com",
  "firstName":"Hello",
  "lastName":"Hello5"
}


###
GET http://localhost:8083/api/v1/users
Accept: application/json

###
GET http://localhost:8083/api/v1/users/99e1a1ab-abca-4243-bbf3-520c55eca15f
Accept: application/json
